version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qweasdyxc
      POSTGRES_DB: test_db
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - :5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    network_mode: "host"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - :80


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    network_mode: "host"
    ports:
        - :5672
        - :15672
